#!/bin/env bash

CMD=$(which hg) ; [ -z $CMD ] && echo 'Install mercurial(hg) and retry...' && exit 1
URL=$1 ; shift
DIR=$1 ; shift

if [ -e "$DIR" ]; then
    ( cd "$DIR" && $CMD "$@" )
else
    $CMD clone "$URL" "$DIR"
fi

exit
